[build]
  publish = "frontend"

[[redirects]]
  from = "/api/products"
  to = "http://beckmnm.atwebpages.com/backend/product_api.php"
  status = 200

[[redirects]]
  from = "/api/cart"
  to = "http://beckmnm.atwebpages.com/backend/cart_api.php"
  status = 200
